defaults: &defaults
  docker:
    - image: circleci/php:latest
  working_directory: ~/project13

ignoreBranches: &ignoreBranches
  filters:
    branches:
      ignore:
        - main
        - circleci-pipeline-setup


deployDev: &deployDev
  filters:
    branches:
      only:
        - circleci-pipeline-setup

deployMain: &deployMain
  filters:
    branches:
      only:
        - main

deploy: &deploy
  name: Deploy Over SSH
  command: |
    set -e
    ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    export BRANCH=$CIRCLE_BRANCH
    echo SendEnv DOCROOT BRANCH >> ~/.ssh/config
    ssh $SSH_USER@$SSH_HOST 'bash -s' < scripts/deploy.sh
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

  deploy:dev:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            echo "export DOCROOT=$DOCROOT_DEV" >> $BASH_ENV
            echo "export SSH_USER=$SSH_USER_DEV" >> $BASH_ENV
            echo "export SSH_HOST=$SSH_HOST_DEV" >> $BASH_ENV
      - run:
          <<: *deploy

  deploy:master:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            echo "export DOCROOT=$DOCROOT_MASTER" >> $BASH_ENV
            echo "export SSH_USER=$SSH_USER_MASTER" >> $BASH_ENV
            echo "export SSH_HOST=$SSH_HOST_MASTER" >> $BASH_ENV
      - run:
          <<: *deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          <<: *ignoreBranches
      
      - deploy:dev:
          <<: *deployDev

      - deploy:master:
          <<: *deployMain